function amdflw()
{
    root -b -q AMDFlw.C\(4,2\)
    root -b -q AMDFlw.C\(4,3\)
    root -b -q AMDFlw.C\(4,4\)
    root -b -q AMDFlw.C\(4,5\)
    root -b -q AMDFlw.C\(5,2\)
    root -b -q AMDFlw.C\(5,3\)
    root -b -q AMDFlw.C\(5,4\)
    root -b -q AMDFlw.C\(5,5\)
    root -b -q AMDFlw.C\(6,2\)
    root -b -q AMDFlw.C\(6,3\)
    root -b -q AMDFlw.C\(6,4\)
    root -b -q AMDFlw.C\(6,5\)
}